apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: skillometer
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ilyamachetto/skillometer-client:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: skillometer
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080